ingresses:
- "https://yrkesskade-prosessering.dev.intern.nav.no"
env:
- name: CLIENT_ID
  value: "test"
- name: CLIENT_SECRET
  value: "client_secret"
- name: AAD_LOGOUT_REDIRECT_URL
  value: "https://yrkesskade-prosessering.dev.intern.nav.no/oauth2/logout?post_logout_redirect_uri=https://yrkesskade-prosessering.dev.intern.nav.no"
- name: AAD_REDIRECT_URL
  value: "https://yrkesskade-prosessering.dev.intern.nav.no/auth/openid/callback"
- name: AAD_DISCOVERY_URL
  value: "https://yrkesskade-prosessering.dev.intern.nav.no/.well-known/openid-configuration"
- name: ENV
  value: "development"