apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-prosessering
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://familie-prosessering.dev.nav.no"
  azure:
    application:
      enabled: true
      tentant: trygdeetaten.no
      replyURLs:
        - 'https://familie-prosessering.dev.nav.no/auth/openid/callback'
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-iverksett
      external:
        - host: familie-ba-mottak.dev-fss-pub.nais.io
        - host: familie-ba-sak.dev-fss-pub.nais.io
        - host: familie-ks-mottak.dev-fss-pub.nais.io
        - host: familie-ef-mottak.dev-fss-pub.nais.io
        - host: familie-tilbake.dev-fss-pub.nais.io
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  envFrom:
    - secret: familie
    - secret: prosessering